//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryMgmt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryMgmtPocEntities : DbContext
    {
        public inventoryMgmtPocEntities()
            : base("name=inventoryMgmtPocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DC> DCs { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<Project_Nodes_Allocation> Project_Nodes_Allocation { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Rack> Racks { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
