//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Nodes_Allocation
    {
        public string id { get; set; }
        public string node_id { get; set; }
        public string project_id { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Project Project { get; set; }
    }
}
